/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app_jchat_pfm;

import java.io.IOException;
import static java.lang.Thread.sleep;
import java.net.DatagramPacket;
import java.net.InetAddress;
import java.net.MulticastSocket;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.NoSuchProviderException;
import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import reqrep_pfmcop.*;

/**
 *
 * @author isen0
 */
public class FenChat extends javax.swing.JFrame {

    private static String formDate;
    private static String formTime;
    private String currentUser=null;
    private int port;
    private InetAddress adresseGroupe;
    MulticastSocket socketGroupe;
    ThreadReception thr;
    private Vector<MessagePFMCOP> messages = new Vector<>();
    
    /**
     * Creates new form FenChat
     */
    public FenChat() {
        initComponents();
        setLocation(900, 200); 
        setTitle("Application Chat PFM");
        setIcon();
        Affichagedate();
    }
    public FenChat(String userName) {
        initComponents();
        setLocation(900, 200); 
        setTitle("Application Chat PFM");
        setIcon();
        Affichagedate();
        currentUser = userName;
        jLabelResponsable.setText(currentUser);
    }
    public FenChat(String userName, int p, String Address) {
        initComponents();
        setLocation(900, 200); 
        setTitle("Application Chat PFM");
        setIcon();
        Affichagedate();
        currentUser = userName;
        jLabelResponsable.setText(currentUser);
        port = p;
        try
        {
            adresseGroupe = InetAddress.getByName(Address);
            socketGroupe = new MulticastSocket(port);
            socketGroupe.joinGroup(adresseGroupe);
            socketGroupe.setTimeToLive(10);
            
            thr = new ThreadReception(currentUser, socketGroupe, jListMessages);
            thr.start();

            String MsgDebut = currentUser + " a rejoint la conversation";
            
            MessagePFMCOP message = new MessagePFMCOP(MessagePFMCOP.NO_TYPE, currentUser, MsgDebut);
            String stringMessage = message.toStringTokMessage();
            
            DatagramPacket dtg = new DatagramPacket(stringMessage.getBytes(), stringMessage.length(), adresseGroupe, port);
            socketGroupe.send(dtg);
            
        }
        catch (IOException e)
        {
            System.err.println("Erreur de connexion au réseau multicast ! ? [" + e + "]");
            JOptionPane.showMessageDialog(this,"Erreur de connexion au réseau multicast : \n"+ e.getMessage(),"Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jLabelResponsable = new javax.swing.JLabel();
        jLabelTitre = new javax.swing.JLabel();
        jLabelicon1 = new javax.swing.JLabel();
        jButtonEnvoyer = new javax.swing.JButton();
        jLabelTime = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListMessages = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldMessage = new javax.swing.JTextField();
        jRBMessage = new javax.swing.JRadioButton();
        jRBQuestion = new javax.swing.JRadioButton();
        jRBReponse = new javax.swing.JRadioButton();
        jRBEvent = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jLogout = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuAPropos = new javax.swing.JMenuItem();
        jMenuItemLogs = new javax.swing.JMenuItem();
        jMenuAide = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("Current user : ");

        jLabelTitre.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabelTitre.setForeground(new java.awt.Color(0, 153, 0));
        jLabelTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitre.setText("Application Chat PFM");
        jLabelTitre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButtonEnvoyer.setText("Envoyer");
        jButtonEnvoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnvoyerActionPerformed(evt);
            }
        });

        jLabelTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jListMessages.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jListMessages.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jListMessages);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Votre message : ");

        buttonGroup1.add(jRBMessage);
        jRBMessage.setSelected(true);
        jRBMessage.setText("Message");

        buttonGroup1.add(jRBQuestion);
        jRBQuestion.setText("Question");

        buttonGroup1.add(jRBReponse);
        jRBReponse.setText("Reponse");

        buttonGroup1.add(jRBEvent);
        jRBEvent.setText("Event");

        jMenu1.setText("Utilisateurs");

        jLogout.setText("Logout");
        jLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(jLogout);

        jMenuBar1.add(jMenu1);

        jMenu10.setText("A Propos");

        jMenuAPropos.setText("Infos");
        jMenuAPropos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAProposActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuAPropos);

        jMenuItemLogs.setText("Fichier Log");
        jMenuItemLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogsActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItemLogs);

        jMenuAide.setText("Aide");
        jMenuAide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAideActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuAide);

        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                        .addComponent(jLabelTime, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextFieldMessage)
                        .addGap(30, 30, 30)
                        .addComponent(jButtonEnvoyer, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(327, 327, 327)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelicon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRBMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                            .addComponent(jRBQuestion)
                            .addComponent(jRBReponse)
                            .addComponent(jRBEvent))
                        .addGap(24, 24, 24)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelResponsable, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTime, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelicon1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRBMessage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRBQuestion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRBReponse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRBEvent)
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonEnvoyer)
                    .addComponent(jTextFieldMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public final void setIcon()
    {
        String logo1 = FichierConfig.getNomsFichs("discuss");
        ImageIcon image1 = new ImageIcon(logo1);
        jLabelicon1.setText(null);        
        jLabelicon1.setIcon(image1);
    }
    
    public static void Affichagedate()
    {
        Thread t_date = new Thread()
        {
            @Override
            public void run()
            {
                while(true)
                {
                    String datecur = getCurrentDate();
                    jLabelTime.setText(datecur);
                    try
                    {
                        sleep(1000);
                    }
                    catch(InterruptedException ex)
                    {
                        ex.getMessage();
                    }
                }
            }
        };
        t_date.start();
    }
    
    public static String getCurrentDate()
    {
        Date cur_date = new Date();
        String madate = new String();
        
        String str = FichierConfig.getdateConfig();
        
        StringTokenizer st = new StringTokenizer(str, "-");
        formDate = st.nextElement().toString();
        formTime = st.nextElement().toString();
        String form = formDate + " " + formTime;
        
        madate = DateFormat.getDateTimeInstance(DateFormat.SHORT, DateFormat.MEDIUM, Locale.FRANCE).format(cur_date);

        
        return madate;
    }
    
    private void jLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutActionPerformed

        String msgFin = currentUser + " quitte la conversation";
        
        MessagePFMCOP message = new MessagePFMCOP(MessagePFMCOP.NO_TYPE, currentUser, msgFin);
        String stringMessage = message.toStringTokMessage();
        
        DatagramPacket dtg = new DatagramPacket(stringMessage.getBytes(), stringMessage.length(), adresseGroupe, port);
        
        try
        {
            socketGroupe.send(dtg);
            thr.stop();
            socketGroupe.leaveGroup(adresseGroupe);
            System.out.println(" Après socketGroupe.leaveGroup(adresseGroupe);");
            socketGroupe.close();
            System.out.println(" Après socketGroupe.close();");
        }
        catch (IOException e)
        {
            System.err.println("Erreur de deconnexion du réseau multicast ! ? [" + e + "]");
            JOptionPane.showMessageDialog(this,"Erreur de deconnexion du réseau multicast : \n"+ e.getMessage(),"Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        FenLogin.logornot = false;
        jLabelResponsable.setText("");
        this.dispose();
        FenLogin fenlog = new FenLogin(this, rootPaneCheckingEnabled);
        FichierLog.UpdateFich("Déconnection de l'utilisateur" );
        fenlog.setVisible(true);
    }//GEN-LAST:event_jLogoutActionPerformed

    private void jMenuAProposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAProposActionPerformed

        FenAbout about = new FenAbout(this, rootPaneCheckingEnabled);
        FichierLog.UpdateFich("Ouverture fenetre d'a propos " );
        about.setVisible(true);
    }//GEN-LAST:event_jMenuAProposActionPerformed

    private void jMenuItemLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogsActionPerformed
        FenAfficherLog log = new FenAfficherLog(this,rootPaneCheckingEnabled);
        FichierLog.UpdateFich("Ouverture fenêtre des logs " );
        log.setVisible(true);
    }//GEN-LAST:event_jMenuItemLogsActionPerformed

    private void jMenuAideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAideActionPerformed

        FenHelp help = new FenHelp(this, rootPaneCheckingEnabled);
        FichierLog.UpdateFich("Ouverture fenetre help " );
        help.setVisible(true);
    }//GEN-LAST:event_jMenuAideActionPerformed

    private void jButtonEnvoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnvoyerActionPerformed
        // TODO add your handling code here:
        
        if(jTextFieldMessage.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this,"Veuillez entrer un message","Erreur",JOptionPane.ERROR_MESSAGE);
            return;
        }
        MessagePFMCOP message = null;
        if(jRBMessage.isSelected())
        {
            message = new MessagePFMCOP(MessagePFMCOP.NO_TYPE, MessagePFMCOP.generateTag(), currentUser, jTextFieldMessage.getText());
        }
        else if (jRBQuestion.isSelected())
        {
            try
            {
                MessageDigest md = MessageDigest.getInstance(FichierConfig.get("ALGODIGEST"), FichierConfig.get("PROVIDERCODE"));
                md.update(jTextFieldMessage.getText().getBytes());
                byte[] msgDigest = md.digest();
                
                message = new MessagePFMCOP(MessagePFMCOP.POST_QUESTION, MessagePFMCOP.generateTag(), currentUser, jTextFieldMessage.getText(), msgDigest);
                System.out.println("TEST getDigest Question : "+message.getDigest());
            }
            catch(NoSuchAlgorithmException | NoSuchProviderException e)
            {
                System.err.println("Erreur digest creation question ! ? [" + e + "]");
                JOptionPane.showMessageDialog(this,"Erreur lors de la creation de la question : \n"+ e.getMessage(),"Erreur", JOptionPane.ERROR_MESSAGE);
            }
        }
        else if (jRBReponse.isSelected())
        {
            MessagePFMCOP question = jListMessages.getSelectedValue();
            if(question == null || question.getType() != MessagePFMCOP.POST_QUESTION)
            {
                JOptionPane.showMessageDialog(this,"Veuillez sélectionner une question dans le chat","Erreur",JOptionPane.ERROR_MESSAGE);
                return;
            }
            try
            {
                MessageDigest md = MessageDigest.getInstance(FichierConfig.get("ALGODIGEST"), FichierConfig.get("PROVIDERCODE"));
                md.update(question.getContent().getBytes());              
                byte[] localDigest = md.digest();
                //System.out.println("--- TEST DIGEST --- ");
                //System.out.println("question : "+question.getContent());
                //System.out.println("digest question : "+question.getDigest());
                //System.out.println("local digest : "+localDigest);
                if(MessageDigest.isEqual(question.getDigest(), localDigest))
                {
                    message = new MessagePFMCOP(MessagePFMCOP.ANSWER_QUESTION, question.getTag(), currentUser, jTextFieldMessage.getText());
                }
                else
                {
                    System.err.println("Erreur: Les digest ne correpondent pas ! ");
                    JOptionPane.showMessageDialog(this,"Erreur: Les digest ne correpondent pas !","Erreur", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            catch(NoSuchAlgorithmException | NoSuchProviderException e)
            {
                System.err.println("Erreur digest creation reponse ! ? [" + e + "]");
                JOptionPane.showMessageDialog(this,"Erreur lors de la creation de la reponse : \n"+ e.getMessage(),"Erreur", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
           // message = new MessagePFMCOP(MessagePFMCOP.ANSWER_QUESTION, question.getTag(), currentUser, jTextFieldMessage.getText());
        }
        else if (jRBEvent.isSelected())
        {
            message = new MessagePFMCOP(MessagePFMCOP.POST_EVENT, MessagePFMCOP.generateTag(), currentUser, jTextFieldMessage.getText());
        }
        
        String stringMessage = message.toStringTokMessage();
        DatagramPacket dtg = new DatagramPacket(stringMessage.getBytes(), stringMessage.length(), adresseGroupe, port);
        try
        {
            socketGroupe.send(dtg);
            jTextFieldMessage.setText("");
        }
        catch (IOException e)
        { 
            System.err.println("Erreur lors de l'envoi du message ! ? [" + e + "]");
            JOptionPane.showMessageDialog(this,"Erreur lors de l'envoi du message. Veuillez réessayer \n","Erreur",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_jButtonEnvoyerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenChat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonEnvoyer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabelResponsable;
    public static javax.swing.JLabel jLabelTime;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JLabel jLabelicon1;
    public static javax.swing.JList<MessagePFMCOP> jListMessages;
    private javax.swing.JMenuItem jLogout;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenuItem jMenuAPropos;
    private javax.swing.JMenuItem jMenuAide;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemLogs;
    private javax.swing.JRadioButton jRBEvent;
    private javax.swing.JRadioButton jRBMessage;
    private javax.swing.JRadioButton jRBQuestion;
    private javax.swing.JRadioButton jRBReponse;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldMessage;
    // End of variables declaration//GEN-END:variables
}
