/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app_mouvements;

import static java.lang.Thread.sleep;
import java.net.Socket;
import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;

/**
 *
 * @author isen0
 */
public class FenAppMouvements extends javax.swing.JFrame {

    /**
     * Creates new form FenAppMouvements
     */
    private static String formDate;
    private static String formTime;
    private Socket cliSock=null;
    private String ChargeRecue=null;
    public FenAppMouvements() {
        initComponents();
        setLocation(900, 200); 
        setTitle("Application Mouvements");
        setIcon();
        Affichagedate();
    }
    public FenAppMouvements(Socket loginSock, String ChargeLogin) {
        initComponents();
        setLocation(900, 200); 
        setTitle("Application Mouvements");
        setIcon();
        Affichagedate();
        cliSock = loginSock;
        ChargeRecue = ChargeLogin;
        jLabelResponsable.setText(ChargeRecue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTime = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelResponsable = new javax.swing.JLabel();
        jLabelTitre = new javax.swing.JLabel();
        jLabelicon1 = new javax.swing.JLabel();
        jButtonLorry = new javax.swing.JButton();
        jButtonLorryWR = new javax.swing.JButton();
        jButtonOperations = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jLogout = new javax.swing.JMenuItem();
        jNouveau = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuAPropos = new javax.swing.JMenuItem();
        jMenuItemLogs = new javax.swing.JMenuItem();
        jMenuAide = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 275));
        setPreferredSize(new java.awt.Dimension(760, 505));

        jLabelTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel4.setText("Responsable :");

        jLabelTitre.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabelTitre.setForeground(new java.awt.Color(204, 0, 0));
        jLabelTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitre.setText("Application Mouvements");
        jLabelTitre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelicon1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonLorry.setText("Arrivée d'un camion avec réservation");
        jButtonLorry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLorryActionPerformed(evt);
            }
        });

        jButtonLorryWR.setText("Arrivée d'un camion sans réservation");
        jButtonLorryWR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLorryWRActionPerformed(evt);
            }
        });

        jButtonOperations.setText("Consulter la liste de opérations");
        jButtonOperations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOperationsActionPerformed(evt);
            }
        });

        jMenu1.setText("Utilisateurs");

        jLogout.setText("Logout");
        jLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(jLogout);

        jNouveau.setText("Nouveau");
        jNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNouveauActionPerformed(evt);
            }
        });
        jMenu1.add(jNouveau);

        jMenuBar1.add(jMenu1);

        jMenu10.setText("A Propos");

        jMenuAPropos.setText("Infos");
        jMenuAPropos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAProposActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuAPropos);

        jMenuItemLogs.setText("Fichier Log");
        jMenuItemLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogsActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItemLogs);

        jMenuAide.setText("Aide");
        jMenuAide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAideActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuAide);

        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTime, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelicon1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonLorry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonLorryWR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonOperations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelResponsable, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTime, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTitre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelicon1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonLorry)
                        .addGap(42, 42, 42)
                        .addComponent(jButtonLorryWR)
                        .addGap(42, 42, 42)
                        .addComponent(jButtonOperations)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public final void setIcon()
    {
        String logo1 = FichierConfig.getNomsFichs("camion");
        ImageIcon image1 = new ImageIcon(logo1);
        jLabelicon1.setText(null);        
        jLabelicon1.setIcon(image1);
    }
    
    public static void Affichagedate()
    {
        Thread t_date = new Thread()
        {
            @Override
            public void run()
            {
                while(true)
                {
                    String datecur = getCurrentDate();
                    jLabelTime.setText(datecur);
                    try
                    {
                        sleep(1000);
                    }
                    catch(InterruptedException ex)
                    {
                        ex.getMessage();
                    }
                }
            }
        };
        t_date.start();
    }
    
    public static String getCurrentDate()
    {
        Date cur_date = new Date();
        String madate = new String();
        
        String str = FichierConfig.getdateConfig();
        
        StringTokenizer st = new StringTokenizer(str, "-");
        formDate = st.nextElement().toString();
        formTime = st.nextElement().toString();
        String form = formDate + " " + formTime;
        
        madate = DateFormat.getDateTimeInstance(DateFormat.SHORT, DateFormat.MEDIUM, Locale.FRANCE).format(cur_date);

        
        return madate;
    }
    
    private void jLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutActionPerformed

            FenLogin.logornot = false;
            jLabelResponsable.setText("");
            this.dispose();
            FenLogin fenlog = new FenLogin(this, rootPaneCheckingEnabled, false);
            FichierLog.UpdateFich("Déconnection de l'utilisateur" );
            fenlog.setVisible(true);  

    }//GEN-LAST:event_jLogoutActionPerformed

    private void jNouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNouveauActionPerformed
        FenLogin fenlog = new FenLogin(this, rootPaneCheckingEnabled, true);
        FichierLog.UpdateFich("Ouverture fenetre de nouveau login " );
        fenlog.setVisible(true);
    }//GEN-LAST:event_jNouveauActionPerformed

    private void jMenuAProposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAProposActionPerformed

            FenAbout about = new FenAbout(this, rootPaneCheckingEnabled);
            FichierLog.UpdateFich("Ouverture fenetre d'a propos " );
            about.setVisible(true);

    }//GEN-LAST:event_jMenuAProposActionPerformed

    private void jMenuAideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAideActionPerformed

            FenHelp help = new FenHelp(this, rootPaneCheckingEnabled);
            FichierLog.UpdateFich("Ouverture fenetre d'help " );
            help.setVisible(true);

    }//GEN-LAST:event_jMenuAideActionPerformed

    private void jMenuItemLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogsActionPerformed
        FenAfficherLog log = new FenAfficherLog(this,rootPaneCheckingEnabled);
        FichierLog.UpdateFich("Ouverture fenêtre des logs " );
        log.setVisible(true);
    }//GEN-LAST:event_jMenuItemLogsActionPerformed

    private void jButtonLorryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLorryActionPerformed
        // TODO add your handling code here:
        FenCamionRes camionRes = new FenCamionRes(cliSock);
        FichierLog.UpdateFich("Ouverture fenêtre FenCamion (LORRY WR)" );
        camionRes.setVisible(true);
    }//GEN-LAST:event_jButtonLorryActionPerformed

    private void jButtonLorryWRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLorryWRActionPerformed
        // TODO add your handling code here:
        FenCamion camion = new FenCamion(cliSock);
        FichierLog.UpdateFich("Ouverture fenêtre FenCamion (LORRY WR)" );
        camion.setVisible(true);
    }//GEN-LAST:event_jButtonLorryWRActionPerformed

    private void jButtonOperationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOperationsActionPerformed
        // TODO add your handling code here:
        FenListeOperations op = new FenListeOperations(cliSock);
        FichierLog.UpdateFich("Ouverture fenêtre FenListeOperations" );
        op.setVisible(true);
    }//GEN-LAST:event_jButtonOperationsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenAppMouvements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenAppMouvements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenAppMouvements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenAppMouvements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenAppMouvements().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLorry;
    private javax.swing.JButton jButtonLorryWR;
    private javax.swing.JButton jButtonOperations;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabelResponsable;
    public static javax.swing.JLabel jLabelTime;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JLabel jLabelicon1;
    private javax.swing.JMenuItem jLogout;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenuItem jMenuAPropos;
    private javax.swing.JMenuItem jMenuAide;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemLogs;
    private javax.swing.JMenuItem jNouveau;
    // End of variables declaration//GEN-END:variables
}
