/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app_mouvements;

import database_acces.ConnexionDB;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.net.UnknownHostException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import reqrep_tramap.ReponseTRAMAP;
import reqrep_tramap.RequeteTRAMAP;

/**
 *
 * @author isen0
 */
public class FenCamionRes extends javax.swing.JFrame {

    /**
     * Creates new form FenCamionRes
     */
    private Socket cliSock=null;
    private ResultSet rs;
    private ObjectInputStream ois;
    private ObjectOutputStream oos;
    public static String infosCamion;
    
    public FenCamionRes() {
        initComponents();
        setTitle("INPUT LORRY");
//        AddDestinations();
    }
    
    public FenCamionRes(Socket SocketMouv) {
        initComponents();
        setTitle("INPUT LORRY");
        cliSock = SocketMouv;
//        AddDestinations();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButtonValider = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();
        CamionTextField = new javax.swing.JTextField();
        ContainerTextField = new javax.swing.JTextField();
        PoidsTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonCamion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ReservationTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Poids :");

        jButtonValider.setText("Valider");
        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });

        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });

        CamionTextField.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Arrivée d'un camion avec réservation");

        jLabel2.setText("Infos camion :");

        jButtonCamion.setText("+");
        jButtonCamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCamionActionPerformed(evt);
            }
        });

        jLabel3.setText("Id container :");

        jLabel6.setText("Id réservation :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30)
                                .addComponent(CamionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCamion))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(PoidsTextField)
                                    .addComponent(ContainerTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                    .addComponent(ReservationTextField, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jButtonValider)
                .addGap(67, 67, 67)
                .addComponent(jButtonAnnuler)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CamionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCamion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ReservationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ContainerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PoidsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonValider)
                    .addComponent(jButtonAnnuler))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderActionPerformed
        // TODO add your handling code here:
        System.out.println(" infos camion : "+infosCamion);
        System.out.println(" id Reservation : "+ReservationTextField.getText());
        System.out.println(" id container : "+ContainerTextField.getText());
        System.out.println(" Poids : "+PoidsTextField.getText());
        //System.out.println(" Destination : "+jComboBoxDestinations.getSelectedItem().toString());

        String chargeUtile = infosCamion+"#"+ReservationTextField.getText()+"#"+ContainerTextField.getText()+"#"+PoidsTextField.getText();
        RequeteTRAMAP req = null;
        //req = new RequeteTRAMAP(RequeteTRAMAP.LOGIN, chargeUtile);

        // Connexion au serveur
        ois=null; oos=null; //cliSock = null;
        String adresse = app_mouvements.FichierConfig.get("HOST");
        int port = Integer.parseInt(app_mouvements.FichierConfig.get("PORT_IN"));

        try
        {
            cliSock = new Socket(adresse, port);
            System.out.println("infos socket : "+cliSock.getInetAddress().toString());
        }
        catch (UnknownHostException e)
        {
            System.err.println("Erreur ! Host non trouvé [" + e + "]");
            JOptionPane.showMessageDialog(this,"Erreur de connexion au serveur : " + e.getMessage());
        }
        catch (IOException e)
        {
            System.err.println("Erreur ! Pas de connexion ? [" + e + "]");
            JOptionPane.showMessageDialog(this,"Erreur de connexion au serveur : " + e.getMessage());
        }

        req = new RequeteTRAMAP(RequeteTRAMAP.INPUT_LORRY, chargeUtile);

        try
        {
            System.out.println("Envoi de la requete INPUT_LORRY : "+req.getChargeUtile());
            oos = new ObjectOutputStream(cliSock.getOutputStream());
            oos.writeObject(req);
            oos.flush();
            FichierLog.UpdateFich("Envoi d'une requete de type INPUT_LORRY : " +req.getChargeUtile());
        }
        catch (IOException e)
        { System.err.println("Erreur réseau ? [" + e.getMessage() + "]"); }

        // Lecture de la réponse
        ReponseTRAMAP rep = null;
        try
        {
            ois = new ObjectInputStream(cliSock.getInputStream());
            rep = (ReponseTRAMAP)ois.readObject();
            System.out.println(" *** Reponse reçue : " + rep.getChargeUtile());
            FichierLog.UpdateFich(" Reponse reçue : " + rep.getChargeUtile());

            if(rep.getCode() == ReponseTRAMAP.OK)
            {
                JOptionPane.showMessageDialog(this," Enregistrement effectué avec succès à l'emplacement "+rep.getChargeUtile()+" !! ");
                FichierLog.UpdateFich(" Enregistrement de la requete (LORRY) : "+chargeUtile+" effectué avec succès a l'emplacement "+rep.getChargeUtile()+" !! " );
                this.dispose();
            }
            else if(rep.getCode() == ReponseTRAMAP.WRONG_DATA)
            {
                JOptionPane.showMessageDialog(this,"Donnée erronée : "+rep.getChargeUtile()+"! Veuillez réessayer");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"La réservation : "+req.getChargeUtile()+" n'esxite pas !! Veuillez réessayer");
            }
        }
        catch (ClassNotFoundException e)
        { System.out.println("--- erreur sur la classe = " + e.getMessage()); }
        catch (IOException e)
        { System.out.println("--- erreur IO = " + e.getMessage()); }
    }//GEN-LAST:event_jButtonValiderActionPerformed

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonAnnulerActionPerformed

    private void jButtonCamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCamionActionPerformed
        // TODO add your handling code here:

        FenTransporteurRes fenTrans = new FenTransporteurRes();
        FichierLog.UpdateFich("Ouverture fenetre de nouveau transporteur " );
        fenTrans.setVisible(true);
    }//GEN-LAST:event_jButtonCamionActionPerformed

//    private void AddDestinations()
//    {
//        try
//        {
//            ConnexionDB db = new ConnexionDB(database_acces.FichierConfig.getNomsFichs("configMouv"),"bd_mouvements");
//            
//            db.openConnection();
//            FichierLog.UpdateFich("Connexion a la base de donnees dans FenListeOperations" );
//            
//            rs = null;
//            
//            if(db!=null)
//            {
//            
//                rs = db.select("SELECT ville FROM destinations");
//
//                ResultSetMetaData metaData = rs.getMetaData();
//
//                while(rs.next())
//                {
//                    Vector<String> data = new Vector<>();
//                    for(int cpt = 1; cpt <= metaData.getColumnCount(); cpt++)
//                    {
//                        //System.out.println("rs : " + rs.getString(cpt));
//                        data.add(rs.getString(cpt));
//                    }
//                    //System.out.println("data : " + data);
//                    jComboBoxDestinations.addItem(data.firstElement());
//                }
//
//                db.closeConnection();
//                db = null;
//            }
//            else
//            {
//                System.err.println("Veuillez vous connecter à la base de donnee");
//            }
//        }
//        catch (ClassNotFoundException | SQLException e)
//        {
//            JOptionPane.showMessageDialog(this,"Erreur lors de la connexion à la DB : " + e.getMessage());
//        }
//    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenCamionRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenCamionRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenCamionRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenCamionRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenCamionRes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField CamionTextField;
    public static javax.swing.JTextField ContainerTextField;
    private javax.swing.JTextField PoidsTextField;
    private javax.swing.JTextField ReservationTextField;
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonCamion;
    private javax.swing.JButton jButtonValider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
