/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app_compta;

import database_acces.*;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.net.UnknownHostException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import reqrep_bisamap.ReponseBISAMAP;
import reqrep_bisamap.RequeteBISAMAP;

/**
 *
 * @author isen0
 */
public class FenListeFactures extends javax.swing.JFrame {

    /**
     * Creates new form FenListeFactures
     */
    private Socket cliSock=null;
    private ResultSet rs;
    private ObjectInputStream ois;
    private ObjectOutputStream oos;
    
    public FenListeFactures() {
        initComponents();
        setTitle("Liste Operations");
        AddSocietes();
    }
    
    public FenListeFactures(Socket MouvSocket) {
        initComponents();
        setTitle("Liste Operations");
        cliSock = MouvSocket;
        AddSocietes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonValider = new javax.swing.JButton();
        jButtonQuitter = new javax.swing.JButton();
        DateDebutTextField = new javax.swing.JTextField();
        DateFinTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        RBSociete = new javax.swing.JRadioButton();
        jComboBoxSocietes = new javax.swing.JComboBox<>();
        jButtonLIST_WAITING = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id facture", "Société", "Date facture", "Montant HTVA", "Montant TVAC", "Facture validée", "Validateur", "Facture envoyée", "Type d'envoi", "Facture payée"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Liste des factures");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Intervalle de temps (obligatoire) :");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Date début (yyyy-MM-dd) :");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Date fin (yyyy-MM-dd) :");

        jButtonValider.setText("Valider");
        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });

        jButtonQuitter.setText("Quitter");
        jButtonQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitterActionPerformed(evt);
            }
        });

        jLabel5.setText("Sélectionnez un filtre (optionnel) :");

        RBSociete.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        RBSociete.setText("Société :");
        RBSociete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBSocieteActionPerformed(evt);
            }
        });

        jButtonLIST_WAITING.setText("LIST_WAITING");
        jButtonLIST_WAITING.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLIST_WAITINGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(144, 144, 144))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DateDebutTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DateFinTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(146, 146, 146))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(RBSociete)
                                .addGap(39, 39, 39)
                                .addComponent(jComboBoxSocietes, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonQuitter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonValider, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonLIST_WAITING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(DateDebutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(DateFinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RBSociete)
                            .addComponent(jComboBoxSocietes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonValider)
                    .addComponent(jButtonLIST_WAITING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonQuitter)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RBSocieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBSocieteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBSocieteActionPerformed

    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderActionPerformed
        // TODO add your handling code here:
        
        boolean Test =verifdate(DateDebutTextField.getText());  
        if(Test==false)
        {
            JOptionPane.showMessageDialog(this,"Vous devez entrer une date de début valide avec le format yyy-MM-dd !!");
        }
        else
        {
            System.out.println("Date de début : " + DateDebutTextField.getText());
            boolean Test2 =verifdate(DateFinTextField.getText());  
            if(Test2==false)
            {
                JOptionPane.showMessageDialog(this,"Vous devez entrer une date de fin valide avec le format yyy-MM-dd !!");
            }
            else
            {
                System.out.println("Date de fin : " + DateFinTextField.getText());     
// CODE HERE     
                //System.out.println("infos socket : "+cliSock.getInetAddress().toString());
                
                
                ois=null; oos=null;
                String adresse = app_compta.FichierConfig.get("HOST");
                int port = Integer.parseInt(app_compta.FichierConfig.get("PORT_COMPTA"));
                RequeteBISAMAP req = null;
                
                try
                {
                    cliSock = new Socket(adresse, port);
                    System.out.println("infos socket : "+cliSock.getInetAddress().toString());
                }
                catch (UnknownHostException e)
                { 
                    System.err.println("Erreur ! Host non trouvé [" + e + "]"); 
                    JOptionPane.showMessageDialog(this,"Erreur de connexion au serveur : " + e.getMessage());
                }
                catch (IOException e)
                { 
                    System.err.println("Erreur ! Pas de connexion ? [" + e + "]");
                    JOptionPane.showMessageDialog(this,"Erreur de connexion au serveur : " + e.getMessage());
                }
                
                String chargeUtile = null;

                if(RBSociete.isSelected() == true)
                {
                    chargeUtile = DateDebutTextField.getText()+"#"+DateFinTextField.getText()+"#"+jComboBoxSocietes.getSelectedItem().toString();
                }
                else
                {
                    chargeUtile = DateDebutTextField.getText()+"#"+DateFinTextField.getText()+"#"+"_";
                }
                
                req = null;
                req = new RequeteBISAMAP(RequeteBISAMAP.LIST_BILLS, chargeUtile);
                ois=null; oos=null;
                try
                {
                    System.out.println("Envoi de la requete LIST_BILLS : "+req.getChargeUtile());
                    oos = new ObjectOutputStream(cliSock.getOutputStream());
                    oos.writeObject(req);
                    oos.flush();
                    FichierLog.UpdateFich("Envoi d'une requete de type LIST_BILLS : " +req.getChargeUtile());
                }
                catch (IOException e)
                { System.err.println("Erreur réseau ? [" + e.getMessage() + "]"); }
                
                // Lecture de la réponse
                ReponseBISAMAP rep = null;
                try
                {
                    ois = new ObjectInputStream(cliSock.getInputStream());
                    rep = (ReponseBISAMAP)ois.readObject();
                    System.out.println(" *** Reponse reçue : " + rep.getModel().toString());
                    //FichierLog.UpdateFich(" Reponse reçue : " + rep.getChargeUtile());

                    if(rep.getCode() == ReponseBISAMAP.OK)
                    {
                        this.jTable1.setModel(rep.getModel());
                        FichierLog.UpdateFich(" Requete Liste Operations : "+chargeUtile+" effectué avec succès !! " );
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this,"Erreur de ResultSet avec les données : "+req.getChargeUtile());
                    }
                }
                catch (ClassNotFoundException e)
                { System.out.println("--- erreur sur la classe = " + e.getMessage()); }
                catch (IOException e)
                { System.out.println("--- erreur IO = " + e.getMessage()); }
            }
        }
        
    }//GEN-LAST:event_jButtonValiderActionPerformed

    private DefaultTableModel createModel(ResultSet result) throws SQLException
    {
        ResultSetMetaData metaData = result.getMetaData();
        DefaultTableModel model = new DefaultTableModel();
        for(int cpt = 1; cpt <= metaData.getColumnCount() ;cpt++)
        {
            model.addColumn(metaData.getColumnName(cpt));
        }

        while(result.next())
        {
            Vector<String> data = new Vector<>();
            for(int cpt = 1; cpt <= metaData.getColumnCount(); cpt++)
            {
                System.out.println("rs : " + result.getString(cpt));
                data.add(result.getString(cpt));
            }
            System.out.println("data : " + data);
            model.addRow(data);
        }
        return model;
    }
    
    private void jButtonQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitterActionPerformed
        // TODO add your handling code here:
        
        System.out.println("Fermeture de FenListeOperation");
        this.dispose();
    }//GEN-LAST:event_jButtonQuitterActionPerformed

    private void jButtonLIST_WAITINGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLIST_WAITINGActionPerformed
        // TODO add your handling code here:
        boolean Test =verifdate(DateDebutTextField.getText());  
        if(Test==false)
        {
            JOptionPane.showMessageDialog(this,"Vous devez entrer une date de début valide avec le format yyy-MM-dd !!");
        }
        else
        {
            System.out.println("Date de début : " + DateDebutTextField.getText());
            boolean Test2 =verifdate(DateFinTextField.getText());  
            if(Test2==false)
            {
                JOptionPane.showMessageDialog(this,"Vous devez entrer une date de fin valide avec le format yyy-MM-dd !!");
            }
            else
            {
                System.out.println("Date de fin : " + DateFinTextField.getText());     
// CODE HERE     
                //System.out.println("infos socket : "+cliSock.getInetAddress().toString());
                
                
                ois=null; oos=null;
                String adresse = app_compta.FichierConfig.get("HOST");
                int port = Integer.parseInt(app_compta.FichierConfig.get("PORT_COMPTA"));
                RequeteBISAMAP req = null;
                
                try
                {
                    cliSock = new Socket(adresse, port);
                    System.out.println("infos socket : "+cliSock.getInetAddress().toString());
                }
                catch (UnknownHostException e)
                { 
                    System.err.println("Erreur ! Host non trouvé [" + e + "]"); 
                    JOptionPane.showMessageDialog(this,"Erreur de connexion au serveur : " + e.getMessage());
                }
                catch (IOException e)
                { 
                    System.err.println("Erreur ! Pas de connexion ? [" + e + "]");
                    JOptionPane.showMessageDialog(this,"Erreur de connexion au serveur : " + e.getMessage());
                }
                
                String chargeUtile = null;

                if(RBSociete.isSelected() == true)
                {
                    chargeUtile = DateDebutTextField.getText()+"#"+DateFinTextField.getText()+"#"+jComboBoxSocietes.getSelectedItem().toString();
                }
                else
                {
                    chargeUtile = DateDebutTextField.getText()+"#"+DateFinTextField.getText()+"#"+"_";
                }
                
                        byte[] signature = null;
        //        try
        //        {
        //            System.out.println("VALIDATE_BILL: Acces au KeyStore");
        //            KeyStore clientKS = KeyStore.getInstance(app_compta.FichierConfig.get("KSALGO"), app_compta.FichierConfig.get("PROVIDERCODE"));
        //            System.out.println("VALIDATE_BILL: TEST affichage avant le LOAD");
        //            clientKS.load(new FileInputStream(FenAppCompta.cryptoUtilPath+System.getProperty("file.separator")+ app_compta.FichierConfig.get("KSCLIENTFILE")),app_compta.FichierConfig.get("KSPWD").toCharArray());
        //            
        //            System.out.println("VALIDATE_BILL: Recuperation de la cle privee");
        //            PrivateKey clePrivee;
        //            clePrivee = (PrivateKey) clientKS.getKey("IsenClient", app_compta.FichierConfig.get("KSENTRYPWD").toCharArray());
        //            System.out.println("VALIDATE_BILL: Cle privee recuperee = " + clePrivee.toString());
        //            
        //            System.out.println("VALIDATE_BILL: Instanciation de la signature");
        //            Signature s = Signature.getInstance(app_compta.FichierConfig.get("ALGOSIGNATURE"),app_compta.FichierConfig.get("PROVIDERCODE"));
        //            System.out.println("VALIDATE_BILL: Initialisation de la signature");
        //            s.initSign(clePrivee);
        //            System.out.println("VALIDATE_BILL: Hachage du message");
        //            s.update(charge.getBytes());
        //            System.out.println("VALIDATE_BILL: Generation des bytes");
        //            signature = s.sign();
        //            System.out.println("VALIDATE_BILL: Termine : signature construite");
        //            System.out.println("VALIDATE_BILL: Signature = " + new String(signature));
        //        }
        //        catch (Exception e)
        //        {
        //            System.err.println("Aie aie imprévu " + e.getMessage());
        //        } 
                
                req = null;
                req = new RequeteBISAMAP(RequeteBISAMAP.LIST_WAITING, chargeUtile, signature);
                ois=null; oos=null;
                try
                {
                    System.out.println("Envoi de la requete LIST_BILLS : "+req.getChargeUtile());
                    oos = new ObjectOutputStream(cliSock.getOutputStream());
                    oos.writeObject(req);
                    oos.flush();
                    FichierLog.UpdateFich("Envoi d'une requete de type LIST_BILLS : " +req.getChargeUtile());
                }
                catch (IOException e)
                { System.err.println("Erreur réseau ? [" + e.getMessage() + "]"); }
                
                // Lecture de la réponse
                ReponseBISAMAP rep = null;
                try
                {
                    ois = new ObjectInputStream(cliSock.getInputStream());
                    rep = (ReponseBISAMAP)ois.readObject();
                    System.out.println(" *** Reponse reçue : " + rep.getModel().toString());
                    //FichierLog.UpdateFich(" Reponse reçue : " + rep.getChargeUtile());

                    if(rep.getCode() == ReponseBISAMAP.OK)
                    {
                        this.jTable1.setModel(rep.getModel());
                        FichierLog.UpdateFich(" Requete Liste Operations : "+chargeUtile+" effectué avec succès !! " );
                    }
                    else if(rep.getCode() == ReponseBISAMAP.FAIL_VERIF)
                    {
                        System.out.println(" Echec de la verification de la signature");
                        FichierLog.UpdateFich(" Echec de la verification de la signature : "+chargeUtile+" effectué avec succès !! " );
                        JOptionPane.showMessageDialog(this,"Echec de la verification de la signature avec les données : "+req.getChargeUtile());
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this,"Erreur de ResultSet avec les données : "+req.getChargeUtile());
                    }
                }
                catch (ClassNotFoundException e)
                { System.out.println("--- erreur sur la classe = " + e.getMessage()); }
                catch (IOException e)
                { System.out.println("--- erreur IO = " + e.getMessage()); }
            }
        }
    }//GEN-LAST:event_jButtonLIST_WAITINGActionPerformed

    public boolean verifdate(String chaine)
    {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        sdf.setLenient(false);

        try {

           //if not valid, it will throw ParseException
            Date date = sdf.parse(chaine);
            System.out.println(date);

        } catch (ParseException e) {

            e.printStackTrace();
            return false;
        }

        return true;
    }
    
    private void AddSocietes()
    {
        try
        {
            ConnexionDB db = new ConnexionDB(database_acces.FichierConfig.getNomsFichs("configCompta"),"bd_mouvements");
            
            db.openConnection();
            FichierLog.UpdateFich("Connexion a la base de donnees dans FenListeOperations" );
            
            rs = null;
            
            if(db!=null)
            {
            
                rs = db.select("SELECT id FROM societes");

                ResultSetMetaData metaData = rs.getMetaData();

                while(rs.next())
                {
                    Vector<String> data = new Vector<>();
                    for(int cpt = 1; cpt <= metaData.getColumnCount(); cpt++)
                    {
                        //System.out.println("rs : " + rs.getString(cpt));
                        data.add(rs.getString(cpt));
                    }
                    //System.out.println("data : " + data);
                    jComboBoxSocietes.addItem(data.firstElement());
                }

                db.closeConnection();
                db = null;
            }
            else
            {
                System.err.println("Veuillez vous connecter à la base de donnee");
            }
        }
        catch (ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(this,"Erreur lors de la connexion à la DB : " + e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenListeFactures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenListeFactures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenListeFactures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenListeFactures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenListeFactures().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DateDebutTextField;
    private javax.swing.JTextField DateFinTextField;
    private javax.swing.JRadioButton RBSociete;
    private javax.swing.JButton jButtonLIST_WAITING;
    private javax.swing.JButton jButtonQuitter;
    private javax.swing.JButton jButtonValider;
    private javax.swing.JComboBox<String> jComboBoxSocietes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
