/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import database_acces.ConnexionDB;
import static java.lang.Thread.sleep;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.StringTokenizer;
import java.util.Vector;

import database_acces.FichierConfig;
import database_acces.FichierLog;

/**
 *
 * @author isen0
 */
public class TestJDBC extends javax.swing.JFrame {

    /**
     * Creates new form TestJDBC
     */
    
    private static String formDate;
    private static String formTime;
    private ConnexionDB db = null;
    
    private ResultSet rs;
    
    public TestJDBC() {
        initComponents();
        Affichagedate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonBDConnect = new javax.swing.JButton();
        jButtonValider = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();
        jTextFieldRequete = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButtonDecoDB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Test d'accès aux bases de données");
        jLabel1.setToolTipText("");

        jLabel2.setText("Requete SQL simple : ");

        jButtonBDConnect.setText("Connexion DB");
        jButtonBDConnect.setMaximumSize(new java.awt.Dimension(123, 32));
        jButtonBDConnect.setMinimumSize(new java.awt.Dimension(123, 32));
        jButtonBDConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBDConnectActionPerformed(evt);
            }
        });

        jButtonValider.setText("Valider");
        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });

        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });

        jTextFieldRequete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRequeteActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButtonDecoDB.setText("Déconnexion DB");
        jButtonDecoDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecoDBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonBDConnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDecoDB)
                                .addGap(28, 28, 28)
                                .addComponent(jButtonValider, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldRequete, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRequete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonValider)
                    .addComponent(jButtonAnnuler)
                    .addComponent(jButtonBDConnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDecoDB))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldRequeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRequeteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRequeteActionPerformed

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
        // TODO add your handling code here:
        this.jTable1.setModel(new DefaultTableModel());
        this.jTextFieldRequete.setText("");
    }//GEN-LAST:event_jButtonAnnulerActionPerformed

    private void jButtonBDConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBDConnectActionPerformed
        // TODO add your handling code here:
        
        try
        {
            db = new ConnexionDB(database_acces.FichierConfig.getNomsFichs("config"),"bd_mouvements");
            db.openConnection();
            
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"En attente d'une requete"},
                {"Connexion à la base de donnée..."},
            },
            new String [] {
                "Messages"
            }
            ));
        
            FichierLog.UpdateFich("Connexion a la base de donnees dans test JDBC" );
        }
        catch (ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(this,"Erreur lors de la connexion à la DB : " + e.getMessage());
        }
       
    }//GEN-LAST:event_jButtonBDConnectActionPerformed

    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderActionPerformed
        // TODO add your handling code here:
        try
        {
            if(db != null)
            {
                String[] elemreq = jTextFieldRequete.getText().split(" ");
                switch(elemreq[0].toUpperCase())
                {
                    case "SELECT" :
                        rs = db.select(jTextFieldRequete.getText());
                        this.jTable1.setModel(this.createModel(rs));
                        break;
                    case "UPDATE" :
                        JOptionPane.showMessageDialog(this,"Nombres de ligne(s) modifiée(s) : " + db.update(jTextFieldRequete.getText()));
                        break;
                    case "INSERT":
                        db.insert(jTextFieldRequete.getText());
                        JOptionPane.showMessageDialog(this,"Ligne(s) inserée(s)");
                        break;
                    default:
                        JOptionPane.showMessageDialog(this,"La requête n'est pas autorisée");
                        break;
                }
                FichierLog.UpdateFich("Requete < "+ jTextFieldRequete.getText() +" > effectuee dans test JDBC" );
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Veuillez vous connecter à la base de donnee");
            }
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(this,"Erreur lors de la requete : " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonValiderActionPerformed

    private void jButtonDecoDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDecoDBActionPerformed
        // TODO add your handling code here:
        if (db != null)
        {
            try
            {
                db.closeConnection();
                db = null;
                this.jTable1.setModel(new DefaultTableModel());
                this.jTextFieldRequete.setText("");
                FichierLog.UpdateFich("Deconnexion de la base de donnees dans test JDBC" );
            }
            catch (SQLException e)
            {
                JOptionPane.showMessageDialog(this,"Erreur lors de la deconnexion de la BD : " + e.getMessage());
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Vous êtes déjà déconnecté !");
        }
    }//GEN-LAST:event_jButtonDecoDBActionPerformed

    private DefaultTableModel createModel(ResultSet result) throws SQLException
    {
        ResultSetMetaData metaData = result.getMetaData();
        DefaultTableModel model = new DefaultTableModel();
        for(int cpt = 1; cpt <= metaData.getColumnCount() ;cpt++)
        {
            model.addColumn(metaData.getColumnName(cpt));
        }

        while(result.next())
        {
            Vector<String> data = new Vector<>();
            for(int cpt = 1; cpt <= metaData.getColumnCount(); cpt++)
            {
                System.out.println("rs : " + result.getString(cpt));
                data.add(result.getString(cpt));
            }
            System.out.println("data : " + data);
            model.addRow(data);
        }
        return model;
    }
    
    public static void Affichagedate()
    {
        Thread t_date = new Thread()
        {
            @Override
            public void run()
            {
                while(true)
                {
                    String datecur = getCurrentDate();
                    jLabel3.setText(datecur);
                    try
                    {
                        sleep(1000);
                    }
                    catch(InterruptedException ex)
                    {
                        ex.getMessage();
                    }
                }
            }
        };
        t_date.start();
    }
         
    public static String getCurrentDate()
    {
        Date cur_date = new Date();
        String madate = new String();
        
        String str = FichierConfig.getdateConfig();
        
        StringTokenizer st = new StringTokenizer(str, "-");
        formDate = st.nextElement().toString();
        formTime = st.nextElement().toString();
        String form = formDate + " " + formTime;
        
        madate = DateFormat.getDateTimeInstance(DateFormat.SHORT, DateFormat.MEDIUM, Locale.FRANCE).format(cur_date);

        
        return madate;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestJDBC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestJDBC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestJDBC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestJDBC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestJDBC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonBDConnect;
    private javax.swing.JButton jButtonDecoDB;
    private javax.swing.JButton jButtonValider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldRequete;
    // End of variables declaration//GEN-END:variables
}
